- name: modify notify_slack
  template:
    src: notify_slack
    dest: /etc/init.d/notify_slack
    owner: root
    group: root
    mode: 0755

- name: notify_slack is enabled
  service:
    name: notify_slack
    enabled: yes
